### ISSUE TITLE
Mismatch between the current graph and the graph from the checkpoint

### ISSUE THREAD

**Issue by brasanko** [cuguilke/microexpnet#13]
I have managed to train your model on my own data, meaning the .data, .meta, .index and information about the last checkpoint have successfully been saved. However I am not able to use this new trained model with the exampleUsage.py file. According to the following error I have problems with the new dimensions of training photos.

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [48,8] rhs shape= [256,8]
         [[{{node save/Assign_7}} = Assign[T=DT_FLOAT, _class=["loc:@wo"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](wo, save/RestoreV2/_15)]]

I am indeed a newbie in tensorflow and so I don't know how to solve this issue. Do I have to retrain the model again and before the training resize to the same photos size as CK+ photos (although it seems that the code reshapes the input photos by itself) or I have to change the exampleUsage.py file? Or I have to do something else?

**Comment by cuguilke** [comment]
Do you use candidate experiments codes or just MicroExpNet with exampleUsage?
