### ISSUE TITLE
How to identify the expression of a face image

### ISSUE THREAD

**Issue by zhuyong999** [cuguilke/microexpnet#4]
Hi
    i want to recognize the expression of a face image,  but I'm not sure how to use these functions. can you give me  a example?
    
  thanks

**Comment by cuguilke** [comment]
You can find an example script for that now.

**Comment by zhuyong999** [comment]
hi 
    I modified the example script  according to   exampleUsage.py,  Why I get the real time image through the camera to test, the result is very unstable, happy still can, the other expression accuracy rate is not high. Can you give me some advice

**Comment by cuguilke** [comment]
Training or fine-tuning the model with more data will help in your case. For example, you can fuse the datasets available for you (some of them have restricted usage policies) in the literature and train a model on that mixture, and this time you can select a preprocessing step for face images considering the settings of your camera. Or if you can gather additional FER data with your camera and then fine-tune a model, it would improve the overall performance you get.

**Comment by zhuyong999** [comment]
thanks， 
 how to  fine-turning?  
  the MicroExpNet is used in the example ,when  fine-turning the model ,which model to use?  the trainCandidates.py  not use the  MicroExpNet  model .  under the /models/OuluCASIA/ , MicroExpNet_OuluCASIA.data-00000-of-00001,MicroExpNet_OuluCASIA.index,and MicroExpNet_OuluCASIA.meta, which is the premodel?
thanks
