### ISSUE TITLE
some question about the paper

### ISSUE THREAD

**Issue by zhanglaplace** [cuguilke/microexpnet#6]
hi ,thanks for you great job in facial expression recognition.
but i have some question.
1 . the network param . M network as a examples
   params: 1\*8\*8\*16+16\*4\*4\*32+32\*11\*11\*3872+3872\*48+48\*8 , not equal 1002808
2 . the preprocess methods of train samples, as the paper show ,the vanilla models compared with state of the art algorithm before could have a better result , why. the small network could get such great result
3 .  training without teacher campared to the knowledge distillation, the result is close when the model is M or S.

**Comment by cuguilke** [comment]
1) The correct calculation is: (8 * 8 * 1 * 16 + 4 * 4 * 16 * 32 + 3872 * 256 + 256 * 8) + (16 + 32 + 256 + 8) = 1002808
* First part of the summation is the number of parameters for weights and the second part is the number of parameters for biases. 
* Conv layers basically have filter-like weights, hence 4*4, 16 is the depth (for example RGB images have depth of 3), 32 is the number of neurons. (for the second conv layer)
* You can check [cs231](http://cs231n.github.io/convolutional-networks/) lecture of Stanford on convnets for more details.

2) I don't understand the question, perhaps, try Google translate?

3) It seems that those models have large enough parameter counts to solve the problem, so knowledge distillation or specifically the value of the temperature T does not effect their performance significantly. This also applies to pooling vs no-pooling experiments.

**Comment by zhanglaplace** [comment]
@cuguilke sorry i mistake the flatten for full connection.
